apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
<<<<<<< Updated upstream
        image: <todo>
=======
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-00-f93a15bdd369/my-repository/hello-cloudbuild-dev:v1.0
>>>>>>> Stashed changes
        ports:
        - containerPort: 8080
